refactor(ec-admin-settings-form): replacing antd with bootstrap 4
ecomplus/admin-marketplace pull request #123
Opened 2020-09-10 12:36 UTC by fabioguieiro

2020-09-10 23:23 UTC, leomp12 requested changes
Boa noite @fabioguieiro ,

Já tinha comentado com você mas revisei aqui pra conseguir mostrar no código, não cheguei olhar detalhes, por enquanto só pontuei o que vi de mais importante.

A sua proposta atual da PR certamente está dando uma avacalhada no funcionamento do componente, dá uma olhada na configuração do app dos Correios por exemplo, ele tem um array de objetos que com as alterações aqui não seria mais tratado...

:v:

2020-09-10 23:23 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> +            :is="checkComplexSchema(schema) && field === config.field ? 'div' : 'div'"
Se é  `? 'div' : 'div'` você podia só remover o `<component>` aqui e usar um `<div>`, não?

2020-09-10 23:23 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> -          <div :key="formResetKey">
Não era pra remover isso aqui não, vai dar uns bugs em schemas mais complexos...

2020-09-10 23:23 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> -              />
Isso aqui precisa continuar como está, ele que vai rederizar o input ou o grupo de inputs respectivo ao campo no loop.

2020-09-10 23:23 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> +            </div>
Isso aqui já está sendo tratado no JS, inclusive tem um bocado de condições a mais :stuck_out_tongue: 
Não precisamos deste trecho aqui, em vez disto era pra ser mantido o:

```vue
<component
  v-bind="{ name, schema }"
  v-model="data[field]"
  :is="component"
/>
```

Os inputs precisam ser editados sim pra removermos elementos e classes do Ant, mas isto deve ser feito em `src/components/_inputs/Input*.vue`.

> Na verdade é mais simples do que o que você começou a fazer aqui...

2020-09-20 01:41 UTC, leomp12 requested changes
Acho que ainda precisamos de um grau aqui @fabioguieiro , comentei os primeiros componentes apenas, mas dá uma olhada nas mesmas coisas nos outros também por favor. Se tiver em dúvida marcamos uma call segunda.

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputBoolean.vue
> +      :value="$Boolean(schema.default)"
`$Boolean` ? Não deu erro aqui?

```suggestion
      :value="Boolean(schema.default)"
```

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputBoolean.vue
> -    :class="localValue && name.indexOf('disable') > -1 ? 'bg-warning' : null"
Esse ponto de usar `.bg-warning` em certos casos é importante, acho que dá pra fazer no checkbox mesmo se você usar alguns inline styles com o `var(--warning)`, se não temos que fixar o switch e padrão e usar ele mesmo em vez de checkbox, e mudar a cor pra warning nessa condição aí..

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDate.vue
> +  >
Aqui você está removendo uma feature, o cleave na verdade não é um componente do `antdv`, é um formatador de input, continuamos importando ele e devemos continuar usando se não o input fica sem formatação (neste caso aqui de data).

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDateTime.vue
> +  </div>
O `<input-date>` e o `<input-time>` são componentes locais nosso, de novo envolvendo formatação, devem continuar sendo usados...

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDate.vue
> +  >
Não tinha alteração nenhuma a ser feita aqui :stuck_out_tongue:

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDiscount.vue
> +    <div>
Se eu não me engano um `<a-form-item>` é respectivo a um `.form-group` do Bootstrap, não? Acho que faltou a classe aqui.

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDiscount.vue
>        <a-input-group compact>
`<a-input-group compact>` não usaremos mais

2020-09-20 01:41 UTC, leomp12 commented on src/components/_inputs/InputDiscount.vue
> +      {{ discountValue.description || discountValue.title}}
O `:extra` do `<a-form-item>` acredito que seria relativo ao [help text](https://getbootstrap.com/docs/4.5/components/forms/#help-text) do form do Bootstrap, aqui ele ficou quase como um label, não era bem isso...

2020-09-20 01:41 UTC, leomp12 commented
Deu uns conflitos na PR também :neutral_face:

2020-10-02 15:56 UTC, leomp12 requested changes
Fala @fabioguieiro ,
Tem uns problemas blocantes aqui ainda :disappointed: 

Acho que você ainda tem que dar uma varrida na [referência do Bootstrap](https://getbootstrap.com/docs/4.5/components/) pra conhecer melhor os componentes dele, onde e como usar.

Também tem algumas coisas que foram removidas na refatoração e que na verdade precisamos manter,  vou precisar de mais uma varrida sua aqui por favor.

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputBoolean.vue
> +  </div>
Não precisava de `.input-group` aqui porque na verdade você tem um input só, não um grupo né..
Não tem prepend nem append nenhum ao input, as divs e classes que você usou na verdade não eram necessárias, o que deveria ser usado mesmo era o custom checkbox do Bootstrap, exemplo aqui https://getbootstrap.com/docs/4.5/components/forms/#checkboxes

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputDiscount.vue
> +    <div class="form-group d-flex">
Acho que aqui sim deveria ter um input group porque aqui sim você tem múltiplos inputs, eg.: https://getbootstrap.com/docs/4.5/components/input-group/#multiple-inputs

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputEnum.vue
> +    class="form-control"
Aqui na verdade deveria ser um `.custom-select` https://getbootstrap.com/docs/4.5/components/forms/#select-menu

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputList.vue
> +    class="form-control mt-2"
Não tá duplicando o `.form-control`? Já tem ele embutido no `InputText`

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputText.vue
> -    :pattern="schema.pattern"
Comeu o `:pattern` com angu :stuck_out_tongue:

2020-10-02 15:56 UTC, leomp12 commented on src/components/_inputs/InputText.vue
> -    :pattern="schema.pattern"
Precisamos que ele continue no input, isso é um atributo padrão do input mesmo, não é do componente do ant não

2020-10-02 15:56 UTC, leomp12 commented on src/components/js/EcAdminSettingsForm.js
> +      console.log(fieldObjects)
```suggestion
```

2020-10-02 15:56 UTC, leomp12 commented on src/components/js/EcAdminSettingsForm.js
> +  },
```suggestion
  
  components:{
    BCollapse
  },

  directives: {
    VBToggle
  },
```

> Só code style mesmo aqui...

2020-10-02 15:56 UTC, leomp12 commented on src/components/js/EcApplication.js
> +      this.popoverShow = false
```suggestion
```

Acho que aqui foi só puxado da outra PR, mas no fim das contas esse método não está sendo usado lá, dei uns fixes no componente antes do merge...

2020-10-02 15:56 UTC, leomp12 commented on src/components/js/EcAdminSettingsForm.js
> +import {BCollapse, VBToggle} from 'bootstrap-vue'
```suggestion
import { BCollapse, VBToggle } from 'bootstrap-vue'
```

2020-10-02 15:56 UTC, leomp12 commented on src/components/js/EcAdminSettingsForm.js
> +import {BCollapse, VBToggle} from 'bootstrap-vue'
:nail_care:

2020-10-02 15:56 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
>                :is="checkComplexSchema(schema) && field === config.field ? 'div' : 'a-form-item'"
```suggestion
              :is="checkComplexSchema(schema) && field === config.field ? 'div' : 'a-form-item'"
```

Não usamos `a-form-item` mais, certo? Aqui deve ficar só `div` mesmo eu acho, talvez nem precisa mais ser um `<component>` dinâmico.

2020-10-02 15:56 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> +              :label="schema.type === 'boolean'? '' : schema.title || field"
Esse `:label` era uma prop do `<a-form-item>`, temos que colocar em algum outro lugar agora...

2020-10-02 15:56 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
>                >
```suggestion
              <div class="mt-3 mb-4 list-group">
```

`:data-source` era uma prop do `<a-list>`...

2020-10-02 15:56 UTC, leomp12 commented on src/components/html/EcAdminSettingsForm.html
> +              slot="message"
Devia ter um `v-html="getDescriptionHtml(description)"` aqui também, não? Antes tinha...

2020-10-02 18:38 UTC, fabioguieiro commented on src/components/js/EcAdminSettingsForm.js
> +  },
essa sugestão de correção compromete o funcionamento do collapse

2020-10-02 20:57 UTC, leomp12 commented on src/components/_inputs/InputBoolean.vue
> +    :value="Boolean(schema.default)">
Isso deu certo @fabioguieiro ? Chegou a testar com um app que tenha um checkbox com default e depois foi alterando? Não sei se vai funcionar corretamente tendo `:value` e `v-model` ao mesmo tempo no mesmo input...

2020-10-09 21:11 UTC, leomp12 approved these changes
Valeu @fabioguieiro :green_apple:

2020-10-09 21:12 UTC, merged