[WIP] Feature to update app version
ecomplus/admin-marketplace pull request #148
Opened 2021-01-29 07:26 UTC by thiagoabreudev

2021-01-29 13:06 UTC, leomp12 requested changes

2021-01-29 13:06 UTC, leomp12 commented on src/worker.js
> +  ecomAuth.login(username, password, storeId).then(() => {
Talvez em web worker o `ecomAuth` não seja o mesmo do web app (não sei se tem tipo um "shadow dom" pra web worker), nesse caso ele não estaria logado aqui e aí você teria que passar o `ecomAuth` no payload do evento, mas sendo sincero eu não vi vantagem em usar web worker aqui (de qualquer forma o evento só é chamado em ocasiões específicas com o app está aberto), alguma razão em específico @thiagoabreudev ?

2021-01-29 13:38 UTC, thiagoabreudev commented on src/components/js/EcAppsMarket.js
> +      const storeId = localStorage.getItem('store_id') || 1056
Preciso sim, poi eu tô usando Web Worker, e o com ele eu não pode passar a instância da thread principal para o worker.

2021-01-29 13:43 UTC, thiagoabreudev commented on src/worker.js
> +  ecomAuth.login(username, password, storeId).then(() => {
Eu escolhi web worker pra ele fazer o processamento em background sem correr o risco de travar a UI do cara em caso de muitos apps a serem atualizados. Sobre passar o ecomAuth no payload, isso não é possível pois ele sempre faz um clone do objeto e neste caso ele não consegue fazer o clone do ecomAuth.

2021-01-29 14:27 UTC, leomp12 commented on src/worker.js
> +  ecomAuth.login(username, password, storeId).then(() => {
Tendi, mas não vai ter como você refazer o login do cara :neutral_face: 
Por que não dá pra clonar o `ecomAuth`?
De qualquer forma, acho que você poderia fazer uma fila disso e fazer sempre um a um após cada idle:

```js
const queuedApps = []

const nextAppUpdate = () => {
  // ...
  if (!queuedApps.length) {
    return
  }
  if (typeof window.requestIdleCallback === 'function') {
    window.requestIdleCallback(nextAppUpdate)
  } else {
    setTimeout(nextAppUpdate, 300)
  }
}

export const queueUpdateApps = (marketApps, installedApps) => {
  if (/* out of date */) {
    queuedApps.push(app)
  }
}
```

2021-02-04 06:07 UTC, thiagoabreudev commented on src/components/js/EcAppsMarket.js
> +      const storeId = localStorage.getItem('store_id') || 1056
Ajustado, foi removido o web work e agora estou usando `requestIdleCallback`

2021-02-04 06:07 UTC, thiagoabreudev commented on src/worker.js
> +  ecomAuth.login(username, password, storeId).then(() => {
Ajustado de acordo com a proposta

2021-02-04 06:11 UTC, thiagoabreudev commented on src/worker.js
> +      listInstalledApps({ ecomApps, marketApps })
Apesar de ter mudado bastante esta parte do código, requisitar a lista de apps instalados se tornou uma necessidade uma vez que o EcAppsMarket só busca os apps instalados se o usuário clicar na aba **Seus apps instalados**.

2021-02-09 16:42 UTC, leomp12 reviewed
Não vi um erro, mas acho que podemos melhorar umas coisas aqui @thiagoabreudev

2021-02-09 16:42 UTC, leomp12 commented on src/components/EcAppCard.vue
> +  }
Nomes de classes não devem ser tão genéricos, use sempre o nome do componente como prefixo, mas na verdade nesse caso acho que nem precisava criar classe nenhuma :grimacing:

2021-02-09 16:42 UTC, leomp12 commented on src/components/EcAppCard.vue
> +</style>
```suggestion
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcAppCard.html
> +  <div class="outdated-label alert alert-warning" v-if="newVersionAvailable">
```suggestion
  <div
    v-if="newVersionAvailable"
    class="w-100 position-absolute alert alert-warning"
  >
```

Em apps como o admin marketplace que não precisamos nos preocupar com customização de tema pelo lojista ou parceiro, é melhor usar utility classes ou até mesmo inline styles (quando não houver classe utilitária), simplifica...

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcApplication.html
> +                <div class="mb-10" v-if="application.newVersionAvailable && isInstalled">
```suggestion
                <div
                  v-if="application.newVersionAvailable && isInstalled"
                  class="mb-10"
                >
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/js/EcApplication.js
> +          this.application.newVersionAvailable = false
Não se deve editar uma prop diretamente (`application` é uma prop).
Além disso, mesmo se estivesse no `data`, o `application` indicaria o body do app, não é uma boa adicionar um field inválid no objeto (fora do schema) porque ele pode ser usado em outros casos e provavelmente não vamos lembrar disso até ver o erro :neutral_face:

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcApplication.html
> +              {{ i19newVersionAvailableMsg}}
```suggestion
              {{ i19newVersionAvailableMsg }}
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcApplication.html
> +              <i class="fa fa-warning" style="font-size: 32px;"> </i>
```suggestion
              <i class="fa fa-warning" style="font-size: 32px;"></i>
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcApplication.html
> +        <div class="alert alert-warning" v-if="application.newVersionAvailable">
```suggestion
        <div
          v-if="application.newVersionAvailable"
          class="alert alert-warning"
        >
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/js/EcApplication.js
> +    i19attention: () => `${i18n(i19attention)}`.toUpperCase(),
```suggestion
    i19attention: () => i18n(i19attention).toUpperCase(),
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/js/EcApplication.js
> +        .catch(e => console.log(e))
```suggestion
        .catch(console.error)
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/js/EcApplication.js
> +    fetchStoreApplication (appId = false) {
```suggestion
    fetchStoreApplication (appId) {
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcApplication.html
> +              <strong>{{ i19attention }}:</strong> {{ i19warningToReinstallAppMsg }}!
```suggestion
              <strong>{{ i19attention }}:</strong> {{ i19warningToReinstallAppMsg }}
```

É melhor que o `...Msg` já contenha as pontuações porque isso também vai variar entre as linguagens posteriormente.

2021-02-09 16:42 UTC, leomp12 commented on src/components/html/EcAppsMarket.html
> +              :newVersionAvailable="appsToUpdate.includes(app.app_id || app.id)"
```suggestion
              :new-version-available="appsToUpdate.includes(app.app_id || app.id)"
```

2021-02-09 16:42 UTC, leomp12 commented on src/components/js/EcAppCard.js
>      }
Quando definindo API de componente, é melhor que booleanos tenham prefixo `is`, `has` ou `can`

2021-02-09 16:42 UTC, leomp12 commented on src/views/js/Application.js
> +        newVersionAvailable: this.$route.params.newVersionAvailable
Isso não precisa ser enviado em prop porque de qualquer forma no `EcApplication` vamos bater o app na API do Market e na Store API, logo você vai ter as duas versões poderia comparar lá mesmo.
De toda forma se quiser passar como prop, deveria ser outra prop (eg.: `hasNewVersion`), não dentro do objeto `application`, que deveria respeitar o modelo [_Application Object_](https://developers.e-com.plus/docs/api/#/store/applications/application-object)

2021-02-12 15:22 UTC, leomp12 submitted a review, later dismissed
Valeu @thiagoabreudev, vou dar merge e um release já, mas ainda deixei uns comentários pra uma próxima PR :stuck_out_tongue:

2021-02-12 15:22 UTC, leomp12 commented on src/components/html/EcAppsMarket.html
> +              @click="$emit('click:app', app, appsToUpdate)"
Isso aqui funciona?
Acho que o evento do Vue emite só um argumento (payload), não? :thinking:

2021-02-12 15:22 UTC, leomp12 commented on src/components/html/EcApplication.html
> +        <div class="alert alert-warning" v-if="hasNewVersion">
```suggestion
        <div
          v-if="hasNewVersion"
          class="alert alert-warning"
        >
```

2021-02-12 15:22 UTC, leomp12 commented on src/components/js/EcApplication.js
> +          if (storeApp && storeApp.version !== data.version) {
Acho que o ideal era conferir se minor ou path e tentar um auto update aqui também quando possível

2021-02-12 15:22 UTC, leomp12 commented on src/components/js/EcInstalledAppCard.js
>      }
```suggestion
    hasNewVersion: Boolean
```

2021-02-12 15:22 UTC, leomp12 commented on src/components/js/EcInstalledAppCard.js
>      }
Se o `default` é false não é necessário explicitar

2021-02-12 15:22 UTC, leomp12 commented on vue.config.js
> +
```suggestion
```

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +/* eslint-disable camelcase */
:neutral_face:

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +/* eslint-disable camelcase */
Faz isso não sô, só quando realmente necessário

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +    .catch((error) => Promise.reject(error))
Isso aqui vai dar fatal

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +    .catch((error) => Promise.reject(error))
No fim das contas tá ficando uma rejeição sem catch

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +    .catch((error) => Promise.reject(error))
```suggestion
    .catch(console.error)
```

2021-02-12 15:22 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +    return ecomApps.findOnMarket(outdatedApp.app_id)
Você tinha o `marketApps`, precisava bater a API de novo?

2021-02-12 15:23 UTC, leomp12 approved these changes

2021-02-12 15:27 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +        store_app.version_date = new Date(store_app.version_date)
Pra quê isso aqui? kk
Você tá pegando um ISO parseado pra objeto Date, mas aí não faz nada com o objeto e quando vai persar o corpo da request pra JSON isso volta pra ISO, então acho que essa linha aqui não faz nada, faz?

2021-02-12 15:27 UTC, leomp12 commented on src/lib/auto-update-apps.js
> +        store_app.version_date = new Date(store_app.version_date)
```suggestion
```

2021-02-12 15:28 UTC, merged