chore(input-list): list category and insert children if has
ecomplus/admin-marketplace pull request #275
Opened 2023-07-02 23:12 UTC by matheusgnreis

![image](https://github.com/ecomplus/admin-marketplace/assets/35343551/e4429b15-5103-430b-bede-6535b65a67dc)

![image](https://github.com/ecomplus/admin-marketplace/assets/35343551/66f14cfc-90d8-4e04-813f-8cbadc111a1e)

![image](https://github.com/ecomplus/admin-marketplace/assets/35343551/1fa55f27-c5b7-4179-bb42-de9a7c9c83de)

2023-07-04 00:54 UTC, leomp12 requested changes

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/InputList.vue
> +      @input="(value, extraValue) => setItemValue(value, i, extraValue)"
Onde você viu isso? 🤔

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/InputList.vue
> +      @input="(value, extraValue) => setItemValue(value, i, extraValue)"
Em geral eventos tem `name` e `value`, além disso o input é um evento padrão do DOM então isso aqui tá muito anti-pattern eu acho

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/InputList.vue
> +      @input="(value, extraValue) => setItemValue(value, i, extraValue)"
Se realmente necessário, seu `value` aí que deveria ser um array provavelmente, não adicionar outro `value`...

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/InputList.vue
> +      @input="(value, extraValue) => setItemValue(value, i, extraValue)"
Não tenho certeza se isso atrapalharia o input text padrão inclusive

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/js/InputCategory.js
> +                this.$emit('blur')
Algum motivo pra repetir o blur?

```suggestion
```

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/js/InputCategory.js
> +                this.$emit('input', category._id, category.parent)
E se houverem 2 subcategorias? Acho que isso aqui nao vai funcionar não, pelo que eu vi vai ficar só uma subcategoria..

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/js/InputList.js
> +        this.localValue.push(item)
Também não sei se esse segundo (ou N) push pro mesmo input poderia dar BO com os próximos inputs na mesma lista, testou isso?

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/InputCategory.vue
> +    :serializer="({ name, parent }) => `${name} ${parent && parent.name ? `(${parent.name})` : ''}`"
```suggestion
    :serializer="({ name, parent }) => `${name} ${(parent && parent.name ? '(' + parent.name + ')' : '')}`"
```

Você testou isso aí ? Parece que tem um erro de sintaxe aí 🙃

2023-07-04 00:54 UTC, leomp12 commented on src/components/_inputs/js/InputList.js
> +        this.localValue.push(item)
> Pra te falar a verdade também não acho necessário buscar as subcategorias automaticamente não, se der problema deixa sem...

2023-07-13 04:51 UTC, matheusgnreis commented on src/components/_inputs/InputCategory.vue
> +    :serializer="({ name, parent }) => `${name} ${parent && parent.name ? `(${parent.name})` : ''}`"
rodei aqui, apareceu certinho em parenteses e tal

2023-07-13 04:52 UTC, matheusgnreis commented on src/components/_inputs/js/InputList.js
> +        this.localValue.push(item)
Testei, foi tranquilo

2023-07-13 04:54 UTC, matheusgnreis commented on src/components/_inputs/InputList.vue
> +      @input="(value, extraValue) => setItemValue(value, i, extraValue)"
Vou testar isso de novo, não lembro exatamente a necessidade, mas lembro de estar dando algum pau, por isso comecei a enviar um extravalue, vou pesquisar os padroes

2023-07-13 04:57 UTC, matheusgnreis commented
Minha duvida maior seria por exemplo buscar todas categorias e buscar pelo nome varrendo array e depois parent id, ou dessa forma ai pra evitar 2 requests seguidas

2024-01-04 02:26 UTC, closed without merging